name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: latest
        
    - name: Install dependencies
      run: |
        quarto install tinytex
        
    - name: Render
      run: quarto render
      
    - name: Copy files to root
      run: |
        ls -la _site/
        cp _site/index.html ./
        cp _site/styles.css ./
        cp -r _site/site_libs ./
        ls -la ./
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 